export const choices = [
  "carpet diem",
  "rug salesman",
  "yasmin",
  "fridge",
  "diply",
  "diplywife",
  "email",
  "shtiner",
  "puff",
  "anal",
  "bacon",
  "el dorado",
  "pool man",
  "horsey games",
  "incel",
  "wallet rule",
  "nye",
  "piccle",
  "duke",
  "overinvested",
  "shaq",
  "ngmi",
  "gmi",
  "space",
  "moonboi",
  "kanye east",
  "comes from above",
  "rasins",
  "captain kelly",
  "personally",
  "gimmethekushbaby",
  "zany",
  "lawyer crow",
  "crane juice",
  "five pillars",
  "battle cranes",
  "halo 7",
  "pelosi",
  "arab money",
  "rich korean jew midget",
  "bruno",
  "solano",
  "ethereum",
  "omegle",
  "disaster",
  "financially ruined",
  "vr",
  "3d",
  "peach",
  "69",
  "420",
  "horsey",
  "hot dog hans",
  "beanie",
  "hd punks",
  "jellyfish",
  "dain",
  "potted plant",
  "buying tops",
  "world war two",
  "cat food",
  "dog food",
  "vomit",
  "wasabi onion",
  "puff",
  "ass girl",
  "volcano",
  "moan space",
  "citrus",
  "smule",
  "autorap",
  "bright eyes",
  "the big short",
  "roasted",
  "pepe",
  "gn",
  "gm",
  "nft bro",
  "twitter",
  "mnd",
  "hard rock nick",
  "butter",
  "kanye east",
  "kanye west",
  "miles",
  "thread",
  "moon boi",
  "liquid",
  "bundles",
  "fortnite",
  "lemon pepper shrimp",
  "prince lemon",
  "prince pepper",
  "prince shrimp",
  "evil bn",
  "nft",
  "opensea",
  "pool boy",
  "tinybed",
  "omegle",
  "team nova",
  "horse",
  "horse",
  "acm",
  "dayjob",
  "wet hands",
  "gmi",
  "ngmi",
  "wen video",
  "gas",
  "phantom",
  "owen",
  "dog food",
  "cat food",
  "vomit",
  "big macs",
  "anal",
  "ledger",
  "heart and soul",
  "discord cord cord",
  "19 eth",
  "$5 a week",
  "up only",
  "wen nft dividend",
  "zeeple dome",
  "spike",
  "tesla",
  "el dorado",
  "steamed crab",
  "kek",
  "kekw",
  "kobe",
  "daisy",
  "mnd",
  "stop the mint",
  "riot",
  "bean dip",
  "knitted cap",
  "i just shit myself",
  "nounphunks",
  "ray cism",
  "dayjob",
  "handjob",
  "smegma",
  "waterboy",
  "tarantula",
  "lore",
  "tendies",
  "rug",
  "owen",
  "pedigree",
  "iphone 11 pro max in gold",
  "ass cream man",
  "mint",
  "rug salesmen",
  "lets fucking go",
  "14 bedroom house",
  "trampoline",
  "donut",
  "pasta",
  "eligibor",
  "phone",
  "goose",
  "football",
  "crane",
  "croissant",
  "crane coin",
  "iladies",
  "tums",
  "beat juice",
  "spice milk",
  "mansion",
  "yacht",
  "shaq",
  "shaq.sol",
  "five pillars",
  "jew",
  "obtuse",
  "acute",
  "pass",
  "diarrhea",
  "pleasure",
  "klondike bars",
  "wifey",
  "astrophysicist",
  "wedge",
  "duke nukem",
  "ponzi",
  "candice",
  "heliopause",
  "pony",
  "papa",
  "tasha",
  "Kaptinkellyfuckedparents",
  "mistakes",
  "xena",
  "milk",
  "my dad",
  "common",
  "peach",
  "bees",
  "breasts",
  "schlappin",
  "vagina",
  "mice",
  "words",
  "cardboard panda",
  "black paper",
  "i eat ass",
  "buying tops",
  "ray charles was my dad",
  "canada dry",
  "sol price",
  "bing bong",
  "pizza planet",
  "jet ski",
  "boomer",
  "spam",
  "ca caw",
  "limp bizkit",
  "each",
  "hope",
  "canoe",
  "elephantitis",
  "fake os pandas",
  "blank vs guile",
  "supercalifragilisticexpialidocious",
  "popcorn",
  "bag of dicks",
  "delete this nephew",
  "potato",
  "are you single?",
  "womanizer",
  "cankles",
  "neurological",
  "sweatshop",
  "3d sol king",
  "soup",
  "heroin",
  "poodles",
  "frogs",
  "preparation h",
  "back room deals",
  "behind closed doors",
  "we took a vote behind closed doors and think you should leave",
  "custom",
  "broom",
  "subway",
  "break",
  "slices",
  "sun",
  "roblox",
  "green",
  "mosque",
  "incel",
  "synagogue",
  "church",
  "apple cider",
  "mystery meat",
  "focus",
  "mushrooms",
  "diabetes",
  "invest",
  "stonks",
  "double rainbow",
  "rainbow",
  "bees",
  "burger",
  "cheeky nandos",
  "hard rock",
  "swingset",
  "alpha",
  "dog park",
  "dog",
  "we're doing everything",
  "raj",
  "cigarette",
  "ring",
  "weed",
  "money",
  "bank",
  "drugs",
  "fireman",
  "police",
  "car",
  "truck",
  "lion king",
  "aladdin",
  "wagon",
  "zoom",
  "nealo",
  "meme",
  "jellyfish",
  "dain",
  "south park",
  "simpsons",
];
